require("remap")
require("plugins")
require("options")

require("after.plugin.gruvbox")
require("after.plugin.telescope")
require("after.plugin.tree")
require("after.plugin.treesitter")
require("after.plugin.fugitive")
require("after.plugin.lsp")
